---
title: "Spatial Autocorrelation Analysis"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Model 4: SEM CM with Kansas respecifications 
```{r Arg2Ks CMwRks, include=FALSE}
# Purpose        : Fit a SEM model with Argentinian data and apply in KS data
# Maintainer     : Marcos Angelini  (marcos.angelini@wur.nl); 

#==============================================================================#
             #### This code come from SEM_Arg2KS_1.0.R ####
#==============================================================================#

# Libraries ####
library(lavaan)
library(pastecs)
library(utils)
library(lattice)

rm(list=ls()[ls()!="t"])
name <- function(x) { as.data.frame(names(x))}
# chose one


# Dictionary of elements in this script ######
# d = calibration dataset. It comes from replacement_of_NAs.Rm 
#     (different versions: 5.0 to 5.3)
# ST = original mean and standard deviation of all variables
# STt = mean and standard deviation of transformed data
# nor = normalisation funcion (x-mean)/sd
# D = transformed and normalised data
# my.model = lavaan syntax
# my.fit = model fitted
# mod = modification indices (for respecification)
#------------------------------------------------#

e <- read.csv("~/Documents/SEM2DSM1/Paper_2/data/calib.data-5.0.csv")[,c(-1,-20)]
# Descriptive statistics and normality test. ####
round(stat.desc(e,norm = TRUE),3)
# Soil properties does not present strong deviation from normality.
# But some covariates need to be transformed. First, we store original mean and 
# sd in ST
ST.arg <- t(stat.desc(e,norm = TRUE)[c(9,13),])

# Based on normtest.W the following covariates need to be transformed
e$wdist <- e$wdist^0.5
e$maxc <- (e$maxc+20000)^2
e$slope <- e$slope^0.25
e$twi <- log10(e$twi)
e$vdchn <- log10(e$vdchn+10)
e$ndwi.a <- (e$ndwi.a+10)^.3
# New statistics
round(stat.desc(e,norm = TRUE),3)
# New mean and sd
STt.arg <- t(stat.desc(e,norm = TRUE)[c(9,13),])

# standardised data set ####
std <- function(x, st){
  y <- x
  for(i in seq_along(names(x))){
    y[,i] <- (x[,i] - st[i,1]) / st[i,2]
  }
  y
}
Arg <- std(e,STt.arg)
Arg[,1] <- e[,1] 

setwd("~/Documents/SEM2DSM1/Paper_3/data/")
d <- read.csv("KS.data-0.2.csv")[,c(-1)] 
name(d)
names(d)[5:10] <- c("CEC.A","CEC.B","CEC.C","OC.A","OC.B","OC.C")
# remove outlayers
# d <- d[d$idp!=26058,]
# d <- d[d$idp!=22961,]
d <- cbind(d[1],
           d[,colnames(Arg)[2:10]],
           d[11:21])
d <- d[c(-156,-157),]
# Descriptive statistics and normality test. ####
round(stat.desc(d,norm = TRUE),3)
# Soil properties does not present strong deviation from normality.
# But some covariates need to be transformed. First, we store original mean and 
# sd in ST
ST.ks <- t(stat.desc(d,norm = TRUE)[c(9,13),])

# Based on normtest.W the following covariates need to be transformed
d$twi <- log10(d$twi)
d$vdchn <- log10(d$vdchn+10)
d$ndwi.a <- (d$ndwi.a+10)^.3
# OC as log10 of OC
# d$OC.A <- log10(d$OC.A)
# d$OC.B <- log10(d$OC.B)
# d$OC.C <- log10(d$OC.C)

# New statistics
round(stat.desc(d,norm = TRUE),3)
# New mean and sd
STt.ks <- t(stat.desc(d,norm = TRUE)[c(9,13),])

# standardised data set ####
std <- function(x, st){
  y <- x
  for(i in seq_along(names(x))){
    y[,i] <- (x[,i] - st[i,1]) / st[i,2]
  }
  y
}
ks <- std(d,STt.ks)
ks[,1] <- d[,1] 
#######################################

# Model with latent variables ####
## Model (re)specification
my.model.lv <- '
# Measurement model (lamda and epsilon)
#--------------------#
CEC.Ar =~ 1*CEC.A
CEC.Br =~ 1*CEC.B
CEC.Cr =~ 1*CEC.C
OC.Ar =~ 1*OC.A
OC.Br =~ 1*OC.B
OC.Cr =~ 1*OC.C
clay.Ar =~ 1*clay.A
clay.Br =~ 1*clay.B
clay.Cr =~ 1*clay.C
## Measurement error #
CEC.A ~~ 0.05 * CEC.A
CEC.B ~~ 0.05 * CEC.B
CEC.C ~~ 0.05 * CEC.C
OC.A ~~ 0.05 * OC.A
OC.B ~~ 0.05 * OC.B
OC.C ~~ 0.05 * OC.C
clay.A ~~ 0.05 * clay.A
clay.B ~~ 0.05 * clay.B
clay.C ~~ 0.05 *clay.C

#--------------------#
# Structural model (gamma and betta matrices)
#--------------------#
clay.Cr ~ dem + vdchn + X + lstm 
clay.Ar ~ clay.Cr + evisd + lstm + ndwi.b + Y 
clay.Br ~ clay.Ar + clay.Cr + vdchn + twi + ndwi.b + Y 

OC.Ar ~ clay.Ar + evisd + lstm + ndwi.b  
OC.Br ~ OC.Ar + clay.Br + evisd + lstm + ndwi.a + vdchn
OC.Cr ~ OC.Br 

CEC.Ar ~ OC.Ar + clay.Ar 
CEC.Br ~ clay.Br + OC.Br
CEC.Cr ~ clay.Cr + OC.Cr

#------------------#
# Model error covariance (Psi)
#------------------#
CEC.Ar ~~ CEC.Br + CEC.Cr
CEC.Cr ~~ CEC.Br
OC.Cr ~~ 0*CEC.Br + 0*CEC.Cr + 0*CEC.Ar 

#------------------#
# lavaan suggestions
#------------------#
clay.Br  ~    lstm
OC.Ar  ~ clay.Br

CEC.Ar ~~   OC.Ar
OC.Ar ~~   OC.Br
OC.Br ~~   OC.Cr

CEC.Cr  ~  ndwi.a
CEC.Br  ~  ndwi.a
clay.Ar ~~ clay.Cr
#------------------#
'


# Model calibration ####
my.fit.lv.ML <- sem(model = my.model.lv,data = ks, meanstructure = FALSE, 
                    fixed.x = T)

# Model evaluation ####
summary(my.fit.lv.ML, fit.measures=TRUE, rsquare = F)
mod.ks <- modindices(my.fit.lv.ML,sort. = T)
mod.ks[mod.ks$mi>5 & (mod.ks$op == "~"|mod.ks$op == "~~"),] 


# Model validation ####
#### Prediction ####
pre <- cbind(ks[1,], matrix(nrow=1,ncol= 9, data = NA,
                           dimnames = list(NULL,paste0(names(ks)[2:10],".p"))))
a <- pre[-(1:nrow(pre)),c(2:10)] #observed
b <- pre[-(1:nrow(pre)),c(2:10)] #predicted
v <- pre[-(1:nrow(pre)),c(2:10)] #variance(s)
resids <- pre[-(1:nrow(pre)),c(2:10)] #residuals
theta <- pre[-(1:nrow(pre)),c(2:10)] # for mean and median
Var <- pre[-(1:nrow(pre)),c(2:10)] # model variance (constant)

# Loop: cal is calibration data, pre is prediction place
# Matrix dedinition (Section 3.3 2nd paper and Fig. 5) #

# Running Prediction @ i location #
# p is a matrix with the 10 external drivers
for(i in seq_along(ks[,1])){ 
  cal <- ks[-i,]
  pre[i,] <- ks[ i,]
  # Fiting #
  my.fit.lv.ML <- sem(model = my.model.lv,data = cal, fixed.x = T,
                      estimator = "ML")
  
  # Matrix of Beta coefficients
  B <- inspect(my.fit.lv.ML, "est")$beta[1:9,1:9]
  # Identity matrix (Kappa coefficients)
  I <- diag(nrow = 9, ncol = 9)
  # Matrix of Gamma coefficients
  A <- inspect(my.fit.lv.ML, "est")$beta[1:9,10:18]
  # Matrix of Psi coefficients (model error variance-covariance)
  V <- inspect(my.fit.lv.ML, "est")$psi[1:9,1:9]
  # Matrix of measurement error (Epsylon)
  Th <- inspect(my.fit.lv.ML, "est")$theta[1:9,1:9]
  IB <- solve(I - B)
  
  # Running Prediction @ i location #
  # p is a matrix with the 10 external drivers
  p = as.vector(as.matrix(pre[i,colnames(A)])) # values of covariates ordered
  p = matrix(p, nrow = 9, ncol = 1)           # by lavaan sequence
  # prediction
  pre[i,22:30] = t(IB %*% A %*% p) # key equation
  # calculate standarised squared standard error
  ## theta is standarised squared standard error
  ## theta = ((observed-predicted)^2)/error variance=(standard error^2)
  a[i,] <- pre[i,c(2:10)] # observed values
  b[i,] <- pre[i,c(22:30)] # predicted values
  v <- diag(IB%*%V%*%t(IB)+Th) # error variance (it is not diagonal!)
  resids[i,] <- a[i,] - b[i,] # residuals
  theta[i,] <- (resids[i,]^2)/v # theta
    # Error variance #
  Var[i,] <- diag(IB %*% V %*% t(IB))
}

# Model variance

summary(Var)
Var <- apply(Var, MARGIN = 2, FUN = mean)

# function to unstandardise the data
unstd<- function(x, st){
  y <- x
  for(i in seq_along(names(x))){
    y[,i] <- (x[,i] * st[i,2]) + st[i,1]
  }
  y
}

# Accuracy measures ####
# Residuals #
Res <- cbind(pre[,1], unstd(pre[,2:10], STt.ks[2:10,]), unstd(pre[,22:30],
                                                           STt.ks[2:10,]))
# # back transform OC
# [,8]<- 10^(pred[,8]+(Var[6]*M$sd[6]^2)*0.5)
# Res[c(5:7)] <- 10^(Res[c(5:7)])
# Res[c(14)] <- 10^(Res[14] + (Var[4] * STt[4 + 1, 2]^2) * 0.5)
# Res[c(15)] <- 10^(Res[15] + (Var[5] * STt[5 + 1, 2]^2) * 0.5)
# Res[c(16)] <- 10^(Res[16] + (Var[6] * STt[6 + 1, 2]^2) * 0.5)

# plot residuals
par(mfrow = c(3, 3), pty="s",mai=rep(0.7,4))

lim.cec <- c(min(cbind(Res[,2:4],Res[,11:13])), max(cbind(Res[,2:4],Res[,11:13])))
lim.oc <- c(min(cbind(Res[,5:7],Res[,14:16])), max(cbind(Res[,5:7],Res[,14:16])))
lim.clay <- c(min(cbind(Res[,8:10],Res[,17:19])), max(cbind(Res[,8:10],Res[,17:19])))

lim <- data.frame(min=NA,max=NA)
lim[1:3,1] <- lim.cec[1]
lim[1:3,2] <- lim.cec[2]
lim[4:6,1] <- lim.oc[1]
lim[4:6,2] <- lim.oc[2]
lim[7:9,1] <- lim.clay[1]
lim[7:9,2] <- lim.clay[2]


for (i in 2:10) {
  limi = c(lim[i-1,1],lim[i-1,2])
  plot(Res[,i+9] ~ Res[,i], main = paste(names(Res)[i]), xlab = "measured",
       ylab = "predicted", col = "dark red", xlim = limi, ylim = limi)
  abline(0,1)
  abline(lm(Res[,i+9] ~ Res[,i]), col = "blue")
}

# create report
report <- data.frame(Soil_property = NA, ME = NA, RMSE = NA, SS = NA,
                     mean_theta = NA, median_th = NA)
for (i in 2:10) {
  # ME <- mean error 
  ME  <-  mean(Res[,i] - Res[,i + 9])
  # RMSE (root mean squared error)
  RMSE <- sqrt(mean((Res[,i] - Res[,i + 9]) ^ 2))
  MSE <- mean((Res[,i] - Res[,i + 9]) ^ 2)
  # SS (Sum of squares)
  SS <- sum((Res[,i] - Res[,i + 9]) ^ 2)
  # fill report table
  report[i-1,1] <- c(names(Res)[i])
  report[i-1,2] <- ME
  report[i-1,3] <- RMSE
  report[i-1,4] <- SS
}

for(i in 1:9){
  report$mean_theta[i] <- mean(theta[,i])
  report$median_th[i] <- median(theta[,i])
}
report
#d.stat <- read.csv("summary.calibdata.csv")
STt.ks <- as.data.frame(STt.ks)
STt.ks$SS <- NA 
for(i in seq_along(names(d))){
  STt.ks$SS[i] <- sum(( d[i] - STt.ks$mean[i])^2)
}

report$R2 <- 1 - (as.numeric(report$SS) / as.numeric(STt.ks$SS[2:10]))
report

# Analysis by Soil Property
# plot mesured vs predicted combined ####par(mfrow = c(1,3), pty="s",mai=rep(0.7,4))
par(mfrow = c(1, 3), pty="s",mai=rep(0.7,4))
rsq<- NULL
CEC <- rbind(as.matrix(Res[,c(2,11)]), as.matrix(Res[,c(3,12)]),
             as.matrix(Res[,c(4,13)]))
colnames(CEC) <- c("CECo","CECp")
rownames(CEC) <- 1:length(rownames(CEC))
CEC <- as.data.frame(CEC)
rsq[1] <- 1 - (sum((CEC$CECo - CEC$CECp)^2)/
                 sum((mean(CEC$CECo)-CEC$CECo)^2))
lim = round(c(min(c(CEC[,1],CEC[,2])), max(c(CEC[,1],CEC[,2]))))
plot(CEC[,2]~CEC[,1], xlim = lim, ylim= lim, xlab = "measured",
     ylab = "predicted", main = "CEC residuals", col = "dark red")
abline(0,1)
abline(lm(CEC[,2]~CEC[,1]),col = "blue")

OC <- rbind(as.matrix(Res[,c(5,14)]), as.matrix(Res[,c(6,15)]),
            as.matrix(Res[,c(7,16)]))
colnames(OC) <- c("OCo","OCp")
rownames(OC) <- 1:length(rownames(OC))
OC <- as.data.frame(OC)
rsq[2] <- 1 - (sum((OC$OCo - OC$OCp)^2)/
                 sum((mean(OC$OCo)-OC$OCo)^2))
lim = round(c(min(c(OC[,1],OC[,2])), max(c(OC[,1],OC[,2]))))
plot(OC[,2]~OC[,1], xlim = lim, ylim= lim, xlab = "measured",
     ylab = "predicted", main = "OC residuals", col = "dark red")
abline(0,1)
abline(lm(OC[,2]~OC[,1]),col = "blue")

clay <- rbind(as.matrix(Res[,c(8,17)]), as.matrix(Res[,c(9,18)]),
              as.matrix(Res[,c(10,19)]))

colnames(clay) <- c("clayo","clayp")
rownames(clay) <- 1:length(rownames(clay))
clay <- as.data.frame(clay)
rsq[3] <- 1 - (sum((clay$clayo - clay$clayp)^2)/
                 sum((mean(clay$clayo)-clay$clayo)^2))
lim = round(c(min(c(clay[,1],clay[,2])), max(c(clay[,1],clay[,2]))))
plot(clay[,2]~clay[,1], xlim = lim, ylim= lim, xlab = "measured",
     ylab = "predicted", main = "Clay residuals", col = "dark red")
abline(0,1)
abline(lm(clay[,2]~clay[,1]),col = "blue")


# create report by soil property
report2 <- data.frame(Soil_property = NA, ME = NA, RMSE = NA, r2 = NA)
z <- cbind(CEC, OC, clay)
for (i in c(1,3,5)) {
  # ME <- mean error 
  ME  <-  mean(z[,i] - z[,i + 1])
  # RMSE (root mean squared error)
  RMSE <- sqrt(mean((z[,i] - z[,i + 1]) ^ 2))
  MSE <- mean((z[,i] - z[,i + 1]) ^ 2)
  # fill report table
  report2[i,1] <- c(names(z)[i])
  report2[i,2:3] <- c(ME, RMSE)
}

report2$r2[1] <- rsq[1]
report2$r2[3] <- rsq[2]
report2$r2[5] <- rsq[3]

report2 <- report2[c(-4,-2),]
report2


################################################################################
library(lattice)

# reshape measured and predicted values for plotting
res <- rbind(as.matrix(Res[,c(2,11)]), as.matrix(Res[,c(3,12)]),
             as.matrix(Res[,c(4,13)]))
res <- rbind(res, as.matrix(Res[,c(5,14)]), as.matrix(Res[,c(6,15)]),
             as.matrix(Res[,c(7,16)]))
res <- rbind(res, as.matrix(Res[,c(8,17)]), as.matrix(Res[,c(9,18)]),
             as.matrix(Res[,c(10,19)]))

rownames(res) <- 1:(156*9)
colnames(res) <- c("observed","predicted")
res <- as.data.frame(res)
res$hor <- rep(c("A", "B", "C"), each= 156,3)
res$sp <- rep(c("CEC", "OC", "clay"), each= 156*3)
res$hor <- as.factor(res$hor)
#levels(res$hor) <- c("C", "B", "A")
```

```{r}
my.model.lv <- '
# Measurement model (lamda and epsilon)
#--------------------#
CEC.Ar =~ 1*CEC.A
CEC.Br =~ 1*CEC.B
CEC.Cr =~ 1*CEC.C
OC.Ar =~ 1*OC.A
OC.Br =~ 1*OC.B
OC.Cr =~ 1*OC.C
clay.Ar =~ 1*clay.A
clay.Br =~ 1*clay.B
clay.Cr =~ 1*clay.C
## Measurement error #
CEC.A ~~ 0.05 * CEC.A
CEC.B ~~ 0.05 * CEC.B
CEC.C ~~ 0.05 * CEC.C
OC.A ~~ 0.05 * OC.A
OC.B ~~ 0.05 * OC.B
OC.C ~~ 0.05 * OC.C
clay.A ~~ 0.05 * clay.A
clay.B ~~ 0.05 * clay.B
clay.C ~~ 0.05 *clay.C

#--------------------#
# Structural model (gamma and betta matrices)
#--------------------#
clay.Cr ~ dem + vdchn + X + lstm 
clay.Ar ~ clay.Cr + evisd + lstm + ndwi.b + Y 
clay.Br ~ clay.Ar + clay.Cr + vdchn + twi + ndwi.b + Y 

OC.Ar ~ clay.Ar + evisd + lstm + ndwi.b  
OC.Br ~ OC.Ar + clay.Br + evisd + lstm + ndwi.a + vdchn
OC.Cr ~ OC.Br 

CEC.Ar ~ OC.Ar + clay.Ar 
CEC.Br ~ clay.Br + OC.Br
CEC.Cr ~ clay.Cr + OC.Cr

#------------------#
# Model error covariance (Psi)
#------------------#
CEC.Ar ~~ CEC.Br + CEC.Cr
CEC.Cr ~~ CEC.Br
OC.Cr ~~ 0*CEC.Br + 0*CEC.Cr + 0*CEC.Ar 

#------------------#
# lavaan suggestions
#------------------#
clay.Br  ~    lstm
OC.Ar  ~ clay.Br

CEC.Ar ~~   OC.Ar
OC.Ar ~~   OC.Br
OC.Br ~~   OC.Cr

CEC.Cr  ~  ndwi.a
CEC.Br  ~  ndwi.a
clay.Ar ~~ clay.Cr
#------------------#
'


# Model calibration ####
my.fit.lv.ML <- sem(model = my.model.lv,data = ks, meanstructure = FALSE, 
                    fixed.x = T)

# Model evaluation ####
summary(my.fit.lv.ML, fit.measures=TRUE, rsquare = F)
mod.ks <- modindices(my.fit.lv.ML,sort. = T)
mod.ks[mod.ks$mi>5 & (mod.ks$op == "~"|mod.ks$op == "~~"),] 
```

##Spatial autocorrelation analysis
### Fitting models
```{r, include=FALSE}
### Autocorrelation in SEM residuals ####
backup <- Res
Res[2:10] <- Res[,2:10]-Res[,11:19]
Res <- Res[,1:10]
names(Res)[1] <- "id.p"

R <- merge(Res, unique(d[,c(1,20,21)]), by.x = "id.p", by.y = "idp", all.x=T)


library(sp)
library(gstat)

# R as geo
coordinates(R) <- ~X+Y

#define crs
wgs84 <- CRS("+init=epsg:4326")
UTM14N <- CRS("+init=epsg:32614")
modis <- CRS("+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs")
NAD83.KS.N <- CRS("+init=epsg:2796")
```

```{r, echo=TRUE}
# Assign projection
proj4string(R) <- NAD83.KS.N

# check zero distance between profiles
zerodist(R, zero=0.0)
R <- remove.duplicates(R, zero = 0.0, remove.second = TRUE)

#R <- spTransform(R, wgs84)
# mapview::viewExtent(R)
#library(mavie)
#mapview(R, burst = TRUE)

###############################
# Variograms
# independent of device size
g <- list()
vg <- list()
vgm <- list()
# CEC.A
g[[1]] <-  gstat(formula = CEC.A ~ 1, data = R)
vg[[1]] <- variogram(g[[1]], width = 7000, cutoff = 450000, cressie = TRUE)
plot(vg[[1]], plot.numbers = TRUE)

# # choose initial variogram model and plot:
vgm[[1]] <- vgm(nugget = 5,
                psill= 30,
                range=100000,
                model = "Exp")
vgm[[1]] <- fit.variogram(vg[[1]], vgm[[1]], fit.method = 6)
plot(vg[[1]], vgm[[1]], main = "CEC.A")
attr(vgm[[1]], "SSErr")

# CEC.B
g[[2]] <-  gstat(formula = CEC.B ~ 1, data = R)
vg[[2]] <- variogram(g[[2]], width = 7000, cutoff = 400000, cressie = TRUE)
plot(vg[[2]], plot.numbers = TRUE)

# # choose initial variogram model and plot:
vgm[[2]] <- vgm(nugget = 5,
                psill= 30,
                range=100000,
                model = "Exp")
vgm[[2]] <- fit.variogram(vg[[2]], vgm[[2]], fit.method = 7)
plot(vg[[2]], vgm[[2]], main = "CEC.B")
attr(vgm[[2]], "SSErr")

# CEC.C
g[[3]] <-  gstat(formula = CEC.C ~ 1, data = R)
vg[[3]] <- variogram(g[[3]], width = 7000, cutoff = 400000, cressie = TRUE)
plot(vg[[3]], plot.numbers = TRUE)

# # choose initial variogram model and plot:
vgm[[3]] <- vgm(nugget = 5,
                psill= 30,
                range=50000,
                model = "Sph")
vgm[[3]] <- fit.variogram(vg[[3]], vgm[[3]], fit.method = 7)
plot(vg[[3]], vgm[[3]], main = "CEC.C")
attr(vgm[[3]], "SSErr")
vgm[[3]]

# OC.A
g[[4]] <-  gstat(formula = OC.A ~ 1, data = R)
vg[[4]] <- variogram(g[[4]], width = 15000, cutoff = 400000, cressie = TRUE)
plot(vg[[4]], plot.numbers = TRUE)

vgm[[4]] <- vgm(nugget = 0.05,
                psill= 0.4,
                range=50000,
                model = "Exp")
vgm[[4]] <- fit.variogram(vg[[4]], vgm[[4]], fit.method = 7)
plot(vg[[4]], vgm[[4]], main = "OC.A")
attr(vgm[[4]], "SSErr")
vgm[[4]]

# OC.B
g[[5]] <-  gstat(formula = OC.B ~ 1, data = R)
vg[[5]] <- variogram(g[[5]], width = 15000, cutoff = 400000, cressie = TRUE)
plot(vg[[5]], plot.numbers = TRUE)

vgm[[5]] <- vgm(nugget = 0,
                psill= 0.8,
                range=20000,
                model = "Exp")
vgm[[5]] <- fit.variogram(vg[[5]], vgm[[5]], fit.method = 7)
plot(vg[[5]], vgm[[5]], main = "OC.B")
attr(vgm[[5]], "SSErr")
vgm[[5]]


# OC.C
g[[6]] <-  gstat(formula = OC.C ~ 1, data = R)
vg[[6]] <- variogram(g[[6]], width = 10000, cutoff = 400000, cressie = TRUE)
plot(vg[[6]], plot.numbers = TRUE)

vgm[[6]] <- vgm(nugget = 0.005,
                psill= 0.02,
                range=20000,
                model = "Gau")
vgm[[6]] <- fit.variogram(vg[[6]], vgm[[6]], fit.method = 2)
plot(vg[[6]], vgm[[6]], main = "OC.C")
attr(vgm[[6]], "SSErr")
vgm[[6]]


# Clay.A
g[[7]] <-  gstat(formula = clay.A ~ 1, data = R)
vg[[7]] <- variogram(g[[7]], width = 7000, cutoff = 400000, cressie = TRUE)
plot(vg[[7]], plot.numbers = TRUE)

vgm[[7]] <- vgm(nugget = 20,
                psill= 80,
                range=100000,
                model = "Exp")
vgm[[7]] <- fit.variogram(vg[[7]], vgm[[7]], fit.method = 1)
plot(vg[[7]], vgm[[7]], main = "Clay.A")
attr(vgm[[7]], "SSErr")
vgm[[7]]

# Clay.B
g[[8]] <-  gstat(formula = clay.B ~ 1, data = R)
vg[[8]] <- variogram(g[[8]], width = 7000, cutoff = 400000, cressie = TRUE)
plot(vg[[8]], plot.numbers = TRUE)

vgm[[8]] <- vgm(nugget = 15,
                psill= 120,
                range=100000,
                model = "Sph")
vgm[[8]] <- fit.variogram(vg[[8]], vgm[[8]], fit.method = 1)
plot(vg[[8]], vgm[[8]], main = "Clay.B")
attr(vgm[[8]], "SSErr")
vgm[[8]]

# Clay.C
g[[9]] <-  gstat(formula = clay.C ~ 1, data = R)
vg[[9]] <- variogram(g[[9]], width = 15000, cutoff = 400000, cressie = TRUE)
plot(vg[[9]], plot.numbers = TRUE)

vgm[[9]] <- vgm(nugget = 20,
                psill= 100,
                range=100000,
                model = "Gau")
vgm[[9]] <- fit.variogram(vg[[9]], vgm[[9]], fit.method = 2)
plot(vg[[9]], vgm[[9]], main = "Clay.C")
attr(vgm[[9]], "SSErr")
vgm[[9]]
```

###Plots
```{r, echo= FALSE}
#############################################################################
# Three graphs (soil properties)
library(lattice)
par(mfrow = c(1, 3), pty = "s")
### CEC
## A
plot(variogramLine(vgm[[1]], maxdist=4E5), 
     type="l", lwd=2,col="#AA0000", main="CEC",
     xlab = "Distance", ylab = "Semivariance", cex.lab = 1.3, ylim=c(0,70)) +
  points(gamma ~ dist, vg[[1]], col="#770000") +
  # B
  lines(variogramLine(vgm[[2]], maxdist=4E5), lwd=2, col="#00AA00") +
  points(gamma ~ dist, vg[[2]], col="#007700", pch = 0) +
  # C
  lines(variogramLine(vgm[[3]], maxdist=4E5), lwd=2, col="#0000AA") +
  points(gamma ~ dist, vg[[3]], col="#000077", pch = 2)

### OC
## A
plot(variogramLine(vgm[[4]], maxdist=4E5), type="l", lwd=2,col="#AA0000", 
     main="OC",
     xlab = "Distance", ylab = "Semivariance", cex.lab = 1.3, ylim=c(0,0.5)) +
  points(gamma ~ dist, vg[[4]], col="#770000") +
  # B
  lines(variogramLine(vgm[[5]], maxdist=4E5), lwd=2, col="#00AA00") + 
  points(gamma ~ dist, vg[[5]], col="#007700", pch = 0) + 
  ## C
  lines(variogramLine(vgm[[6]], maxdist=4E5), lwd=2, col="#0000AA") + 
  points(gamma ~ dist, vg[[6]], col="#000077", pch = 2) 

### Clay
## A
plot(variogramLine(vgm[[7]], maxdist=4E5), type="l", lwd=2,col="#AA0000", 
     main="Clay",
     xlab = "Distance", ylab = "Semivariance", cex.lab = 1.3, ylim=c(0,140)) +
  points(gamma ~ dist, vg[[7]], col="#770000") +
  ## B
  lines(variogramLine(vgm[[8]], maxdist=4E5), lwd=2, col="#00AA00") +
  points(gamma ~ dist, vg[[8]], col="#007700", pch = 0) +
  ## C
  lines(variogramLine(vgm[[9]], maxdist=4E5), lwd=2, col="#0000AA") +
  points(gamma ~ dist, vg[[9]], col="#000077", pch = 2) 
```
### Kriging + predicted
```{r, include=FALSE}
# Krige CV
res <- backup
names(res)[1] <- "id.p"
r <- as.data.frame(R)
for(i in 1:9){
  x <- krige.cv(as.formula(paste0(names(R)[i+1], "~1")),
                R, vgm[[i]])#, debug.level=-1)
  r[,1+i] <- as.data.frame(x)[,1]
}
res <- merge(x = res, y = r, by= "id.p", all.y = T)
res[,11:19] <- res[,11:19] + res[,20:28]

Res <- res[1:19]
```
### Accuracy measures
```{r, include= FALSE}
# plot residuals
par(mfrow = c(3, 3), pty="s",mai=rep(0.7,4))

lim.cec <- c(min(cbind(Res[,2:4],Res[,11:13])), max(cbind(Res[,2:4],Res[,11:13])))
lim.oc <- c(min(cbind(Res[,5:7],Res[,14:16])), max(cbind(Res[,5:7],Res[,14:16])))
lim.clay <- c(min(cbind(Res[,8:10],Res[,17:19])), max(cbind(Res[,8:10],Res[,17:19])))

lim <- data.frame(min=NA,max=NA)
lim[1:3,1] <- lim.cec[1]
lim[1:3,2] <- lim.cec[2]
lim[4:6,1] <- lim.oc[1]
lim[4:6,2] <- lim.oc[2]
lim[7:9,1] <- lim.clay[1]
lim[7:9,2] <- lim.clay[2]


for (i in 2:10) {
  limi = c(lim[i-1,1],lim[i-1,2])
  plot(Res[,i+9] ~ Res[,i], main = paste(names(Res)[i]), xlab = "measured",
       ylab = "predicted", col = "dark red", xlim = limi, ylim = limi) +
    abline(0,1) +
    abline(lm(Res[,i+9] ~ Res[,i]), col = "blue")
}

# create report
report.k <- data.frame(Soil_property = NA, ME = NA, RMSE = NA, SS = NA,
                     mean_theta = NA, median_th = NA)
for (i in 2:10) {
  # ME <- mean error 
  ME  <-  mean(Res[,i] - Res[,i + 9])
  # RMSE (root mean squared error)
  RMSE <- sqrt(mean((Res[,i] - Res[,i + 9]) ^ 2))
  MSE <- mean((Res[,i] - Res[,i + 9]) ^ 2)
  # SS (Sum of squares)
  SS <- sum((Res[,i] - Res[,i + 9]) ^ 2)
  # fill report table
  report.k[i-1,1] <- c(names(Res)[i])
  report.k[i-1,2] <- ME
  report.k[i-1,3] <- RMSE
  report.k[i-1,4] <- SS
}

for(i in 1:9){
  report.k$mean_theta[i] <- mean(theta[,i])
  report.k$median_th[i] <- median(theta[,i])
}
report.k
#d.stat <- read.csv("summary.calibdata.csv")
STt.ks <- as.data.frame(STt.ks)
STt.ks$SS <- NA 
for(i in seq_along(names(d))){
  STt.ks$SS[i] <- sum(( d[i] - STt.ks$mean[i])^2)
}

report.k$R2 <- 1 - (as.numeric(report.k$SS) / as.numeric(STt.ks$SS[2:10]))
report.k

# Analysis by Soil Property
# plot mesured vs predicted combined ####par(mfrow = c(1,3), pty="s",mai=rep(0.7,4))
par(mfrow = c(1, 3), pty="s",mai=rep(0.7,4))
rsq<- NULL
CEC <- rbind(as.matrix(Res[,c(2,11)]), as.matrix(Res[,c(3,12)]),
             as.matrix(Res[,c(4,13)]))
colnames(CEC) <- c("CECo","CECp")

CEC <- as.data.frame(CEC)
rsq[1] <- 1 - (sum((CEC$CECo - CEC$CECp)^2)/
                 sum((mean(CEC$CECo)-CEC$CECo)^2))
lim = round(c(min(c(CEC[,1],CEC[,2])), max(c(CEC[,1],CEC[,2]))))
plot(CEC[,2]~CEC[,1], xlim = lim, ylim= lim, xlab = "measured",
     ylab = "predicted", main = "CEC residuals", col = "dark red") +
  abline(0,1) +
  abline(lm(CEC[,2]~CEC[,1]),col = "blue")

OC <- rbind(as.matrix(Res[,c(5,14)]), as.matrix(Res[,c(6,15)]),
            as.matrix(Res[,c(7,16)])) 
colnames(OC) <- c("OCo","OCp") 

OC <- as.data.frame(OC)
rsq[2] <- 1 - (sum((OC$OCo - OC$OCp)^2)/
                 sum((mean(OC$OCo)-OC$OCo)^2))
lim = round(c(min(c(OC[,1],OC[,2])), max(c(OC[,1],OC[,2]))))
plot(OC[,2]~OC[,1], xlim = lim, ylim= lim, xlab = "measured",
     ylab = "predicted", main = "OC residuals", col = "dark red") +
  abline(0,1) +
  abline(lm(OC[,2]~OC[,1]),col = "blue")

clay <- rbind(as.matrix(Res[,c(8,17)]), as.matrix(Res[,c(9,18)]),
              as.matrix(Res[,c(10,19)]))

colnames(clay) <- c("clayo","clayp")

clay <- as.data.frame(clay)
rsq[3] <- 1 - (sum((clay$clayo - clay$clayp)^2)/
                 sum((mean(clay$clayo)-clay$clayo)^2))
lim = round(c(min(c(clay[,1],clay[,2])), max(c(clay[,1],clay[,2]))))
plot(clay[,2]~clay[,1], xlim = lim, ylim= lim, xlab = "measured",
     ylab = "predicted", main = "Clay residuals", col = "dark red") +
  abline(0,1) +
  abline(lm(clay[,2]~clay[,1]),col = "blue")


# create report by soil property
report2.k <- data.frame(Soil_property = NA, ME = NA, RMSE = NA, r2 = NA)
z <- cbind(CEC, OC, clay)
for (i in c(1,3,5)) {
  # ME <- mean error 
  ME  <-  mean(z[,i] - z[,i + 1])
  # RMSE (root mean squared error)
  RMSE <- sqrt(mean((z[,i] - z[,i + 1]) ^ 2))
  MSE <- mean((z[,i] - z[,i + 1]) ^ 2)
  # fill report table
  report2.k[i,1] <- c(names(z)[i])
  report2.k[i,2:3] <- c(ME, RMSE)
}

report2.k$r2[1] <- rsq[1]
report2.k$r2[3] <- rsq[2]
report2.k$r2[5] <- rsq[3]

report2.k <- report2.k[c(-4,-2),]
report2.k
```

Results
```{r, echo=F }
knitr::kable(report, caption = "Model 4 | hor + sp", digits = 3)
knitr::kable(report2, caption = "Model 4 | sp", digits = 3)
knitr::kable(report.k, caption = "Model 4 + kriging | hor + sp", digits = 3)
knitr::kable(report2.k, caption = "Model 4 + kriging | sp", digits = 3)
knitr::kable(cbind(report[,c(1,7)], report.k[,c(7)]), 
             caption = "Model 4 vs Model 4 + K", digits = 3)
knitr::kable(cbind(report2[,c(1,4)], report2.k[,c(4)]), 
             caption = "Model 4 vs Model 4 + K (by SP)", digits = 3)
```
***********************************